import { useEffect, useRef, type ReactNode } from 'react';
import { ArrowDownLeft, ArrowUpRight, Box, X } from 'lucide-react';
import { dateTime, entryCost, money, quantity } from './format';
import type { Entry, Product } from './types';

export function Modal({ title, subtitle, children, onClose }: { title: string; subtitle?: string; children: ReactNode; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current!; dialog.showModal(); const previous = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { dialog.close(); document.body.style.overflow = previous; }; }, []);
  return <dialog ref={ref} className="modal" onCancel={e => { e.preventDefault(); onClose(); }} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-labelledby="modal-title"><div className="modal-inner"><div className="flex items-start justify-between gap-4"><div><h2 id="modal-title">{title}</h2>{subtitle && <p className="muted mt-2">{subtitle}</p>}</div><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={20} /></button></div>{children}</div></dialog>;
}
export function Empty({ title, detail }: { title: string; detail: string }) { return <div className="empty"><Box size={30} strokeWidth={1.5} /><h3>{title}</h3><p>{detail}</p></div>; }
export function StockBadge({ value }: { value: string }) { const n = BigInt(value); return <span className={`badge ${n === 0n ? 'gray' : n < 25n ? 'amber' : 'green'}`}><i />{n === 0n ? 'Out of stock' : n < 25n ? 'Low stock' : 'In stock'}</span>; }
export function ProductTable({ products, onSelect, loading }: { products: Product[]; onSelect: (product: Product) => void; loading: boolean }) {
  if (loading) return <div className="skeleton-list" aria-label="Loading inventory">{[1, 2, 3, 4].map(i => <div className="skeleton" key={i} />)}</div>;
  if (!products.length) return <Empty title="No products to show" detail="Publish a purchase to add inventory, or adjust your search." />;
  return <div className="table-scroll"><table><thead><tr><th>Product</th><th>Stock on hand</th><th>Inventory value</th><th>Avg. unit cost</th><th>Status</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{products.map((p, i) => <tr key={p.product_id}><td><button className="product-cell" onClick={() => onSelect(p)}><span className={`product-icon tone-${i % 4}`}><Box size={19} /></span><span><strong>{p.product_id}</strong><small>Inventory product</small></span></button></td><td><strong>{quantity(p.current_quantity)}</strong><span className="muted"> units</span></td><td className="tabular-nums font-medium">{money(p.total_inventory_cost)}</td><td className="muted tabular-nums">{money(p.average_cost_per_unit)}</td><td><StockBadge value={p.current_quantity} /></td><td><button className="icon-button" onClick={() => onSelect(p)} aria-label={`View batches for ${p.product_id}`}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table></div>;
}
export function LedgerTable({ entries, onSelect, loading }: { entries: Entry[]; onSelect: (entry: Entry) => void; loading: boolean }) {
  if (loading) return <div className="skeleton-list">{[1, 2, 3].map(i => <div key={i} className="skeleton" />)}</div>;
  if (!entries.length) return <Empty title="Your ledger starts here" detail="Processed purchases and sales will appear automatically." />;
  return <div className="table-scroll"><table><thead><tr><th>Transaction</th><th>Product</th><th>Quantity</th><th>Cost / FIFO cost</th><th>Date & time</th><th>Status</th><th /></tr></thead><tbody>{entries.map(e => <tr key={e.event_id}><td><button className="transaction-cell" onClick={() => onSelect(e)}><span className={`event-icon ${e.event_type}`}>{e.event_type === 'purchase' ? <ArrowDownLeft size={17} /> : <ArrowUpRight size={17} />}</span><strong className="capitalize">{e.event_type}</strong></button></td><td className="font-medium">{e.product_id}</td><td>{e.quantity === null ? '—' : quantity(e.quantity)}</td><td className="tabular-nums font-medium">{entryCost(e) === null ? '—' : money(entryCost(e)!)}</td><td className="muted whitespace-nowrap">{dateTime(e.occurred_at)}</td><td><span className={`badge ${e.status === 'applied' ? 'green' : 'red'}`}><i />{e.status === 'applied' ? 'Completed' : 'Rejected'}</span></td><td><button className="icon-button" aria-label={`View transaction ${e.event_id}`} onClick={() => onSelect(e)}><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div>;
}
export function ActivityChart({ entries }: { entries: Entry[] }) {
  const days = Array.from({ length: 7 }, (_, i) => { const day = new Date(); day.setDate(day.getDate() - 6 + i); const matches = entries.filter(e => e.status === 'applied' && new Date(e.occurred_at).toDateString() === day.toDateString()); return { day, purchase: matches.filter(e => e.event_type === 'purchase').reduce((n, e) => n + (e.quantity || 0), 0), sale: matches.filter(e => e.event_type === 'sale').reduce((n, e) => n + (e.quantity || 0), 0) }; });
  const max = Math.max(10, ...days.flatMap(d => [d.purchase, d.sale]));
  return <div className="chart" role="img" aria-label={`Seven-day stock movement in units. ${days.map(d => `${d.day.toLocaleDateString()}: ${d.purchase} purchased, ${d.sale} sold`).join('. ')}`}><div className="chart-scale">{[1, .75, .5, .25, 0].map(n => <span key={n}>{Math.ceil(max * n)}</span>)}</div><div className="chart-plot"><div className="chart-grid">{[1, 2, 3, 4, 5].map(i => <i key={i} />)}</div><div className="chart-bars">{days.map(({ day, purchase, sale }) => <div className="chart-day" key={day.toISOString()}><div className="bar-pair"><div className="bar purchase-bar" style={{ height: `${purchase / max * 100}%` }} title={`${purchase} units purchased`} /><div className="bar sale-bar" style={{ height: `${sale / max * 100}%` }} title={`${sale} units sold`} /></div><span>{day.toLocaleDateString('en', { weekday: 'short' })}</span></div>)}</div></div></div>;
}
